<?php

$config['CUS_CONFIG'] = 1;

define('IMAGE_TOLERANCE', 0.5);

define('BRAND_LOGO_MAXWIDTH', 200);
define('BRAND_LOGO_MINWIDTH', 120);
define('BRAND_LOGO_MAXHEIGHT', 200);
define('BRAND_LOGO_MINHEIGHT', 100);
define('BRAND_LOGO_MAXSIZE', 1000);
define('BRAND_LOGO_ALLOWEDTYPES', 'jpg|png');


define('NEWS_MAXWIDTH', 600);
define('NEWS_MINWIDTH', 400);
define('NEWS_MAXHEIGHT', 600);
define('NEWS_MINHEIGHT', 400);
define('NEWS_MAXSIZE', 250);
define('NEWS_ALLOWEDTYPES', 'jpg|png');


define('MODEL_MAXWIDTH', 2200);
define('MODEL_MINWIDTH', 2000);
define('MODEL_MAXHEIGHT', 1250);
define('MODEL_MINHEIGHT', 1125);
define('MODEL_MAXSIZE', 1024);
define('MODEL_ALLOWEDTYPES', 'jpg|png');

define('MODEL_ZOOM_MAXWIDTH', 2200);
define('MODEL_ZOOM_MINWIDTH', 1800);
define('MODEL_ZOOM_MAXHEIGHT', 1250);
define('MODEL_ZOOM_MINHEIGHT', 1013);
define('MODEL_ZOOM_MAXSIZE', 768);
define('MODEL_ZOOM_ALLOWEDTYPES', 'jpg|png');

define('MODEL_THUMBNAIL_MAXWIDTH', 2200);
define('MODEL_THUMBNAIL_MINWIDTH', 90);
define('MODEL_THUMBNAIL_MAXHEIGHT', 1250);
define('MODEL_THUMBNAIL_MINHEIGHT', 90);
define('MODEL_THUMBNAIL_MAXSIZE', 512);
define('MODEL_THUMBNAIL_ALLOWEDTYPES', 'jpg|png');

define('ITEM_MAXWIDTH', 2200);
define('ITEM_MINWIDTH', 2000);
define('ITEM_MAXHEIGHT', 1250);
define('ITEM_MINHEIGHT', 1125);
define('ITEM_MAXSIZE', 1024);
define('ITEM_ALLOWEDTYPES', 'jpg|png');

define('ITEM_ZOOM_MAXWIDTH', 2200);
define('ITEM_ZOOM_MINWIDTH', 1800);
define('ITEM_ZOOM_MAXHEIGHT', 1250);
define('ITEM_ZOOM_MINHEIGHT', 1013);
define('ITEM_ZOOM_MAXSIZE', 768);
define('ITEM_ZOOM_ALLOWEDTYPES', 'jpg|png');

define('ITEM_THUMBNAIL_MAXWIDTH', 2200);
define('ITEM_THUMBNAIL_MINWIDTH', 90);
define('ITEM_THUMBNAIL_MAXHEIGHT', 1250);
define('ITEM_THUMBNAIL_MINHEIGHT', 90);
define('ITEM_THUMBNAIL_MAXSIZE', 512);
define('ITEM_THUMBNAIL_ALLOWEDTYPES', 'jpg|png');

define('PRESCRIPTION_MAXWIDTH', 3000);
define('PRESCRIPTION_MINWIDTH', 500);
define('PRESCRIPTION_MAXHEIGHT', 3000);
define('PRESCRIPTION_MINHEIGHT', 500);
define('PRESCRIPTION_MAXSIZE', 3000);
define('PRESCRIPTION_ALLOWEDTYPES', 'jpg|png');

define('PRESCRIPTION_IMAGE_FILE_PATH', 'public/runningimages/prescription/');
define('MODEL_IMAGE_FILE_PATH', 'public/runningimages/model/image/');
define('ITEM_IMAGE_FILE_PATH', 'public/runningimages/item/image/');

define('PAYMENT_STANDARD', 'STANDARD');
define('PAYMENT_SMARTEPAY', 'SMART_EPAY');

define('PAYNOW', 'PAY_NOW');
define('PAY_LATER', 'PAY_LATER');

define('PAYMENT_CASH', 'CASH');
define('PAYMENT_CREDIT_CARD', 'CREDIT_CARD');
define('PAYMENT_CHEQUE', 'CHEQUE');

define('CUSTOMER_ORDER_MAIL_TEMPLATE', 2);
define('CUSTOMER_INVOICE_MAIL_TEMPLATE', 3);

define('INVOICE_STATUS_INVOICED', 'INVOICED');
define('ALLOW_ORDER_OUT_OF_STOCKS', FALSE);
define('SALES_PROCESS_TYPE', 'ONLINE');
