<?php

$config['msg'] = array(
    1 => "Not logged in",
    2 => "Login failed, please check your credentials.",
    3 => "No data found",
    4 => "Please enter the username / recovery email. System will send you a mail with instructions for resetting the password.",
    5 => "Your Password Reset instructions has sent to the given email address.\\nPlease check your email.",
    6 => "Invalid ID.",
    7 => "Item Disabled.",
    8 => "Item Not Found.",
    9 => "Required values not set.",
    10 => "Value already exists.",
    11 => "Do you want to remove this image?",
    12 => "Session Parameters Not Set",
    40 => "Status Updated Successfully.",
    41 => "Status Update Failed.",
    42 => "Are you sure you want to change the status?",
    43 => "Successfully Updated.",
    44 => "Updating Failed.",
    45 => "Cannot edit disabled items. Please enable before editing.",
    46 => "Cannot add values for disabled items. Please enable before add values.",
    //User
    150 => "User added successfully.",
    151 => "User adding failed.",
    152 => "Passwords do not match.",
    153 => "This is recovery email address.",
    154 => "This is recovery phone number.",
    155 => "User update successfully.",
    156 => "User update failed.",
    157 => "Invalid username.",
    158 => "Username / email does not exist in our databases.",
    159 => "Recovery email not found.",
    160 => "Password reset request failed.",
    161 => "Invalid code.",
    162 => "Code has been used.",
    163 => "Code has been expired.",
    164 => "This code is not valid for resetting your password.",
    165 => "Invalid reset code.",
    166 => "Invalid password.",
    167 => "Error while updating password.",
    168 => "Password should be 8 - 20 charactes long.",
    169 => "Password reset success.",
    170 => "Are you sure you want to enable this user?",
    171 => "Are you sure you want to disable this user?",
    //Brands
    200 => "Brand added successfully.",
    201 => "Brand adding failed.",
    202 => "Brand Updated successfully",
    203 => "Brand Update failed.",
    204 => "Are you sure you want to disable this brand?",
    205 => "Are you sure you want to enable this brand?",
    //News
    210 => "News added successfully.",
    211 => "News adding failed.",
    212 => "News Updated successfully",
    213 => "News Update failed.",
    214 => "Are you sure you want to disable this news?",
    215 => "Are you sure you want to enable this news?",
    //Category
    300 => "Category added successfully",
    301 => "Category adding failed",
    302 => "Are you sure you want to disable this category?",
    303 => "Are you sure you want to enable this category?",
    304 => "Category updated successfully",
    305 => "Category update failed",
    //Category
    320 => "Product added successfully",
    321 => "Product adding failed",
    322 => "Are you sure you want to disable this product?",
    323 => "Are you sure you want to enable this product?",
    324 => "Product updated successfully",
    325 => "Product update failed",
    //Branch    
    400 => "Branch added successfully",
    401 => "Branch adding failed",
    402 => "Branch Updated successfully",
    403 => "Branch Update failed.",
    404 => "Are you sure want to enable this branch?",
    405 => "Are you sure want to disable this branch?",
    //Item (Please reserve 440 - 500)
    440 => "Field added successfully.",
    441 => "Field adding failed.",
    442 => "Field name cannot be empty",
    443 => "Error while adding field",
    444 => "Are you sure want to diable this field?",
    445 => "Are you sure want to enable this field?",
    446 => "Field value adding successful",
    447 => "Field value adding faild",
    448 => "Error While Updating Field",
    449 => "Error While Adding Field Value",
    450 => "Are you sure want to diable this field value?",
    451 => "Are you sure want to enable this field value?",
    452 => "Value definition not required for boolean fields",
    453 => "Field id note set.",
    454 => "Are you sure want to diable this sub field?",
    455 => "Are you sure want to enable this sub field?",
    456 => "No sub fields defined. Please add sub fields before adding values.",
    //Colors
    550 => "Color added successfully.",
    551 => "Color adding failed.",
    552 => "Color update successfully.",
    553 => "Color update failed.",
    554 => "Are you sure want to enable this color?",
    555 => "Are you sure want to disable this color?",
    //Model Field Value
    560 => "Model Field Value added successfully.",
    561 => "Model Field Value adding failed.",
    562 => "Model Field Value update successfully.",
    563 => "Model Field Value update failed.",
    564 => "Are you sure want to enable this Model Field Value?",
    565 => "Are you sure want to disable this Model Field Value?",
    566 => "Error While Updateting Model Field Values",
    567 => "Model Field Values Updated Successfully",
    //Items
    568 => "Item Code Cannot be Empty",
    569 => "Item Code Already Exists",
    570 => "Item Check Failed",
    571 => "Error While Updating Item",
    572 => "Cannot view details of disabled items",
    573 => "Are you sure want to enable this item?",
    574 => "Are you sure want to disable this item?",
    575 => "Invlid Model ID",
    576 => "Model Not Found",
    577 => "Item Added Successfully",
    578 => "Item Updated Successfully",
    579 => "Error While Adding Item",
    //Models
    580 => "Are you sure want to disable this Model?",
    581 => "Are you sure want to enable this Model?",
    582 => "Model added successfully.",
    583 => "Model adding failed.",
    584 => "Cannot view details of disabled models.",
    585 => "Model Field Added Succssfully.",
    586 => "Model Field Values Updated Succssfully.",
    587 => "No Field Were Updated.",
    //Supplier
    590 => "Supplier added successfully.",
    591 => "Supplier adding failed.",
    592 => "Supplier update successfully.",
    593 => "Supplier update failed.",
    594 => "Are you sure want to enable this Supplier?",
    595 => "Are you sure want to disable this Supplier?",
    //GRN
    600 => "Invalid item code",
    601 => "Error While Searching Item",
    602 => "Invalid Item Code",
    603 => "Item Not Found",
    604 => "No Item Selected",
    605 => "Invalid Serial Number",
    606 => "Please add items to GRN",
    607 => "GRN added successfully",
    608 => "Error while adding GRN",
    609 => "Are you sure want to enable this GRN?",
    610 => "Are you sure want to disable this GRN?",
    611 => "Quantity Cannot be zero.",
    612 => "GRN not found.",
    //Product Type
    650 => "Product Type added successfully.",
    651 => "Product Type adding failed.",
    652 => "Product Type update successfully.",
    653 => "Product Type update failed.",
    654 => "Are you sure want to enable this Product Type?",
    655 => "Are you sure want to disable this Product Type?",
    //Item Selling Price
    650 => "Selling price cannot be less than cost.",
    651 => "Selling price updated successfully.",
    652 => "Selling price updating failed.",
    653 => "Effective date cannot be passed date.",
    //Shopping Cart
    700 => "Item already selected.",
    701 => "Item added to shopping cart successfully.",
    702 => "Shopping cart item disabled successfully.",
    703 => "Item not found.",
    704 => "Are you sure you want to disable item?",
    705 => "All options shold be selected.",
    706 => "Are you sure you want to enable item?",
    707 => "Cart item updated successfully",
    708 => "Cart item update failed",
    709 => "There are no active items in the cart.",
    710 => "Please sign in before continue.",
    711 => "There are no items in the shopping cart.",
    712 => "There is an issue with the item. Please contact system administrator.",
    713 => "Order ID not found.",
    714 => "Invalid Order ID.",
    715 => "Error while creating order.",
    716 => "Shopping cart is empty.",
    717 => "No matching items found.",
    718 => "Item out of stocks.",
    //Customer Login / Signup
    750 => "Error while creating user",
    751 => "Passwords do not match",
    752 => "Sign-up Successful",
    753 => "Error while user sign-up",
    754 => "Sign-in Success",
    755 => "Sign-in Failed.",
    756 => "Are you sure you want to sign out?",
    757 => "Email already exists in database",
    758 => "Add shipping profile success",
    759 => "Add shipping profile failed",
    760 => "Update shipping profile success",
    761 => "Update shipping profile failed",
    762 => "No shipping profile found",
    763 => "Please select a shipping profile",
    //Image Upload
    1100 => "Error while uploading the image",
    1101 => "File not found",
    1102 => "Invalid upload name.",
    1103 => "Required parameters not set",
    1104 => "Image size less than minimum criteria",
    1105 => "Error while resizing the image",
    1106 => "Error while cropping the image",
    1107 => "No images to update",
    1108 => "Error While Updating Images",
    1109 => "Images Updated Successfully",
    1110 => "Are your sure you want to enable this image?",
    1111 => "Are your sure you want to disable this image?",
    //Invoice
    780 => "Are you sure need to disable this invoice?",
    781 => "Are you sure need to enable this invoice?",
    782 => "Invoice id not found.",
    //Payment
    800 => "Amount should be less than payable amount.",
    801 => "Amount should be greater than 0.",
    //Promotion
    830 => "Item added to promotion successfully.",
    831 => "Item added to promotion failed.",
    832 => "Promotion added successfully.",
    833 => "Promotion added failed.",
    834 => "Promotion update successfully.",
    835 => "Promotion update failed.",
    836 => "Are you sure need to this promotion disable?",
    837 => "Are you sure need to this promotion enable?",
);
